# Generated by Django 4.0.1 on 2022-02-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('insta_Link', models.CharField(max_length=255)),
                ('fb_Link', models.CharField(max_length=255)),
                ('twitter_Link', models.CharField(max_length=255)),
                ('linkedin_Link', models.CharField(max_length=255)),
            ],
        ),
    ]
