# Generated by Django 4.0.1 on 2022-02-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0002_alter_basedetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedetail',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
