# Generated by Django 4.0.1 on 2022-01-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team_alter_slider_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yT_link',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
