# Generated by Django 4.0.1 on 2022-02-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_pargraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='pargraph',
            name='firstptitle',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='pargraph',
            name='secondptitle',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
