# Generated by Django 4.0.1 on 2022-02-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_pargraph_firstptitle_pargraph_secondptitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pargraph',
            name='secondpara',
        ),
        migrations.RemoveField(
            model_name='pargraph',
            name='secondptitle',
        ),
    ]
